/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Status = { 'aktif' : null } |
  { 'alumni' : null };
export interface T {
  'id' : string,
  'status' : Status,
  'alamat' : string,
  'nama' : string,
  'nisn' : string,
  'angkatan' : bigint,
  'kelas' : string,
  'jurusan' : string,
  'fotoId' : string,
}
export interface T__1 {
  'id' : string,
  'tahun' : bigint,
  'judul' : string,
  'deskripsi' : string,
  'tingkat' : { 'nasional' : null } |
    { 'internasional' : null } |
    { 'provinsi' : null } |
    { 'kabupaten' : null } |
    { 'sekolah' : null },
  'siswa' : string,
  'fotoId' : string,
}
export interface T__2 {
  'id' : string,
  'bio' : string,
  'nama' : string,
  'jabatan' : string,
  'urutan' : bigint,
  'mataPelajaran' : string,
  'fotoId' : string,
}
export interface T__3 {
  'id' : string,
  'status' : { 'upcoming' : null } |
    { 'done' : null } |
    { 'ongoing' : null },
  'tanggal' : Time,
  'judul' : string,
  'deskripsi' : string,
  'lokasi' : string,
  'fotoId' : string,
}
export interface T__4 {
  'id' : string,
  'isi' : string,
  'published' : boolean,
  'ringkasan' : string,
  'judul' : string,
  'tanggalPublish' : Time,
  'coverFotoId' : string,
}
export interface T__5 {
  'id' : string,
  'tanggalUpload' : Time,
  'judul' : string,
  'deskripsi' : string,
  'kategori' : string,
  'fotoId' : string,
}
export interface T__6 { 'tujuan' : string, 'misi' : string, 'visi' : string }
export interface T__7 {
  'jamOperasional' : string,
  'alamat' : string,
  'koordinat' : string,
  'email' : string,
  'telepon' : string,
}
export interface T__8 {
  'id' : string,
  'isi' : string,
  'nama' : string,
  'email' : string,
  'subjek' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGaleri' : ActorMethod<[string, T__5], undefined>,
  'addInformasi' : ActorMethod<[string, T__4], undefined>,
  'addKegiatan' : ActorMethod<[string, T__3], undefined>,
  'addPengajar' : ActorMethod<[string, T__2], undefined>,
  'addPrestasi' : ActorMethod<[string, T__1], undefined>,
  'addSiswa' : ActorMethod<[string, T], undefined>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGaleri' : ActorMethod<[string, string], undefined>,
  'deleteInformasi' : ActorMethod<[string, string], undefined>,
  'deleteKegiatan' : ActorMethod<[string, string], undefined>,
  'deletePengajar' : ActorMethod<[string, string], undefined>,
  'deletePrestasi' : ActorMethod<[string, string], undefined>,
  'deleteSiswa' : ActorMethod<[string, string], undefined>,
  'getAllGaleri' : ActorMethod<[], Array<T__5>>,
  'getAllInformasi' : ActorMethod<[string], Array<T__4>>,
  'getAllKegiatan' : ActorMethod<[], Array<T__3>>,
  'getAllPengajar' : ActorMethod<[], Array<T__2>>,
  'getAllPesan' : ActorMethod<[string], Array<T__8>>,
  'getAllPrestasi' : ActorMethod<[], Array<T__1>>,
  'getAllSiswa' : ActorMethod<[string], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGaleriByKategori' : ActorMethod<[string], Array<T__5>>,
  'getKegiatanByStatus' : ActorMethod<
    [{ 'upcoming' : null } | { 'done' : null } | { 'ongoing' : null }],
    Array<T__3>
  >,
  'getKontak' : ActorMethod<[], [] | [T__7]>,
  'getPrestasiByTingkat' : ActorMethod<
    [
      { 'nasional' : null } |
        { 'internasional' : null } |
        { 'provinsi' : null } |
        { 'kabupaten' : null } |
        { 'sekolah' : null },
    ],
    Array<T__1>
  >,
  'getProfil' : ActorMethod<[], [] | [T__6]>,
  'getPublishedInformasi' : ActorMethod<[], Array<T__4>>,
  'getSiswaByKelas' : ActorMethod<[string, string], Array<T>>,
  'getSiswaByStatus' : ActorMethod<[string, Status], Array<T>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSessionValid' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendPesan' : ActorMethod<[string, string, string, string, Time], undefined>,
  'setAdminCredentials' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateGaleri' : ActorMethod<[string, string, T__5], undefined>,
  'updateInformasi' : ActorMethod<[string, string, T__4], undefined>,
  'updateKegiatan' : ActorMethod<[string, string, T__3], undefined>,
  'updateKontak' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updatePengajar' : ActorMethod<[string, string, T__2], undefined>,
  'updatePrestasi' : ActorMethod<[string, string, T__1], undefined>,
  'updateProfil' : ActorMethod<[string, string, string, string], undefined>,
  'updateSiswa' : ActorMethod<[string, string, T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];