/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const T__4 = IDL.Record({
  'id' : IDL.Text,
  'tanggalUpload' : Time,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
  'kategori' : IDL.Text,
  'fotoId' : IDL.Text,
});
export const T__3 = IDL.Record({
  'id' : IDL.Text,
  'isi' : IDL.Text,
  'published' : IDL.Bool,
  'ringkasan' : IDL.Text,
  'judul' : IDL.Text,
  'tanggalPublish' : Time,
  'coverFotoId' : IDL.Text,
});
export const T__2 = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'upcoming' : IDL.Null,
    'done' : IDL.Null,
    'ongoing' : IDL.Null,
  }),
  'tanggal' : Time,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
  'lokasi' : IDL.Text,
  'fotoId' : IDL.Text,
});
export const T__1 = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'nama' : IDL.Text,
  'jabatan' : IDL.Text,
  'urutan' : IDL.Nat,
  'mataPelajaran' : IDL.Text,
  'fotoId' : IDL.Text,
});
export const T = IDL.Record({
  'id' : IDL.Text,
  'tahun' : IDL.Nat,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
  'tingkat' : IDL.Variant({
    'nasional' : IDL.Null,
    'internasional' : IDL.Null,
    'provinsi' : IDL.Null,
    'kabupaten' : IDL.Null,
    'sekolah' : IDL.Null,
  }),
  'siswa' : IDL.Text,
  'fotoId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const T__7 = IDL.Record({
  'id' : IDL.Text,
  'isi' : IDL.Text,
  'nama' : IDL.Text,
  'email' : IDL.Text,
  'subjek' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const T__6 = IDL.Record({
  'jamOperasional' : IDL.Text,
  'alamat' : IDL.Text,
  'koordinat' : IDL.Text,
  'email' : IDL.Text,
  'telepon' : IDL.Text,
});
export const T__5 = IDL.Record({
  'tujuan' : IDL.Text,
  'misi' : IDL.Text,
  'visi' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGaleri' : IDL.Func([T__4], [], []),
  'addInformasi' : IDL.Func([T__3], [], []),
  'addKegiatan' : IDL.Func([T__2], [], []),
  'addPengajar' : IDL.Func([T__1], [], []),
  'addPrestasi' : IDL.Func([T], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGaleri' : IDL.Func([IDL.Text], [], []),
  'deleteInformasi' : IDL.Func([IDL.Text], [], []),
  'deleteKegiatan' : IDL.Func([IDL.Text], [], []),
  'deletePengajar' : IDL.Func([IDL.Text], [], []),
  'deletePrestasi' : IDL.Func([IDL.Text], [], []),
  'getAllGaleri' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
  'getAllInformasi' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getAllKegiatan' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
  'getAllPengajar' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getAllPesan' : IDL.Func([], [IDL.Vec(T__7)], ['query']),
  'getAllPrestasi' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGaleriByKategori' : IDL.Func([IDL.Text], [IDL.Vec(T__4)], ['query']),
  'getKegiatanByStatus' : IDL.Func(
      [
        IDL.Variant({
          'upcoming' : IDL.Null,
          'done' : IDL.Null,
          'ongoing' : IDL.Null,
        }),
      ],
      [IDL.Vec(T__2)],
      ['query'],
    ),
  'getKontak' : IDL.Func([], [IDL.Opt(T__6)], ['query']),
  'getPrestasiByTingkat' : IDL.Func(
      [
        IDL.Variant({
          'nasional' : IDL.Null,
          'internasional' : IDL.Null,
          'provinsi' : IDL.Null,
          'kabupaten' : IDL.Null,
          'sekolah' : IDL.Null,
        }),
      ],
      [IDL.Vec(T)],
      ['query'],
    ),
  'getProfil' : IDL.Func([], [IDL.Opt(T__5)], ['query']),
  'getPublishedInformasi' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendPesan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'updateGaleri' : IDL.Func([IDL.Text, T__4], [], []),
  'updateInformasi' : IDL.Func([IDL.Text, T__3], [], []),
  'updateKegiatan' : IDL.Func([IDL.Text, T__2], [], []),
  'updateKontak' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePengajar' : IDL.Func([IDL.Text, T__1], [], []),
  'updatePrestasi' : IDL.Func([IDL.Text, T], [], []),
  'updateProfil' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const T__4 = IDL.Record({
    'id' : IDL.Text,
    'tanggalUpload' : Time,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
    'kategori' : IDL.Text,
    'fotoId' : IDL.Text,
  });
  const T__3 = IDL.Record({
    'id' : IDL.Text,
    'isi' : IDL.Text,
    'published' : IDL.Bool,
    'ringkasan' : IDL.Text,
    'judul' : IDL.Text,
    'tanggalPublish' : Time,
    'coverFotoId' : IDL.Text,
  });
  const T__2 = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'upcoming' : IDL.Null,
      'done' : IDL.Null,
      'ongoing' : IDL.Null,
    }),
    'tanggal' : Time,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
    'lokasi' : IDL.Text,
    'fotoId' : IDL.Text,
  });
  const T__1 = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'nama' : IDL.Text,
    'jabatan' : IDL.Text,
    'urutan' : IDL.Nat,
    'mataPelajaran' : IDL.Text,
    'fotoId' : IDL.Text,
  });
  const T = IDL.Record({
    'id' : IDL.Text,
    'tahun' : IDL.Nat,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
    'tingkat' : IDL.Variant({
      'nasional' : IDL.Null,
      'internasional' : IDL.Null,
      'provinsi' : IDL.Null,
      'kabupaten' : IDL.Null,
      'sekolah' : IDL.Null,
    }),
    'siswa' : IDL.Text,
    'fotoId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const T__7 = IDL.Record({
    'id' : IDL.Text,
    'isi' : IDL.Text,
    'nama' : IDL.Text,
    'email' : IDL.Text,
    'subjek' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const T__6 = IDL.Record({
    'jamOperasional' : IDL.Text,
    'alamat' : IDL.Text,
    'koordinat' : IDL.Text,
    'email' : IDL.Text,
    'telepon' : IDL.Text,
  });
  const T__5 = IDL.Record({
    'tujuan' : IDL.Text,
    'misi' : IDL.Text,
    'visi' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGaleri' : IDL.Func([T__4], [], []),
    'addInformasi' : IDL.Func([T__3], [], []),
    'addKegiatan' : IDL.Func([T__2], [], []),
    'addPengajar' : IDL.Func([T__1], [], []),
    'addPrestasi' : IDL.Func([T], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGaleri' : IDL.Func([IDL.Text], [], []),
    'deleteInformasi' : IDL.Func([IDL.Text], [], []),
    'deleteKegiatan' : IDL.Func([IDL.Text], [], []),
    'deletePengajar' : IDL.Func([IDL.Text], [], []),
    'deletePrestasi' : IDL.Func([IDL.Text], [], []),
    'getAllGaleri' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
    'getAllInformasi' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getAllKegiatan' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
    'getAllPengajar' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getAllPesan' : IDL.Func([], [IDL.Vec(T__7)], ['query']),
    'getAllPrestasi' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGaleriByKategori' : IDL.Func([IDL.Text], [IDL.Vec(T__4)], ['query']),
    'getKegiatanByStatus' : IDL.Func(
        [
          IDL.Variant({
            'upcoming' : IDL.Null,
            'done' : IDL.Null,
            'ongoing' : IDL.Null,
          }),
        ],
        [IDL.Vec(T__2)],
        ['query'],
      ),
    'getKontak' : IDL.Func([], [IDL.Opt(T__6)], ['query']),
    'getPrestasiByTingkat' : IDL.Func(
        [
          IDL.Variant({
            'nasional' : IDL.Null,
            'internasional' : IDL.Null,
            'provinsi' : IDL.Null,
            'kabupaten' : IDL.Null,
            'sekolah' : IDL.Null,
          }),
        ],
        [IDL.Vec(T)],
        ['query'],
      ),
    'getProfil' : IDL.Func([], [IDL.Opt(T__5)], ['query']),
    'getPublishedInformasi' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendPesan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'updateGaleri' : IDL.Func([IDL.Text, T__4], [], []),
    'updateInformasi' : IDL.Func([IDL.Text, T__3], [], []),
    'updateKegiatan' : IDL.Func([IDL.Text, T__2], [], []),
    'updateKontak' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePengajar' : IDL.Func([IDL.Text, T__1], [], []),
    'updatePrestasi' : IDL.Func([IDL.Text, T], [], []),
    'updateProfil' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };