/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface T__7 {
    jamOperasional: string;
    alamat: string;
    koordinat: string;
    email: string;
    telepon: string;
}
export interface T__8 {
    id: string;
    isi: string;
    nama: string;
    email: string;
    subjek: string;
    timestamp: Time;
}
export interface T__1 {
    id: string;
    tahun: bigint;
    judul: string;
    deskripsi: string;
    tingkat: Variant_nasional_internasional_provinsi_kabupaten_sekolah;
    siswa: string;
    fotoId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface T__4 {
    id: string;
    isi: string;
    published: boolean;
    ringkasan: string;
    judul: string;
    tanggalPublish: Time;
    coverFotoId: string;
}
export interface T__3 {
    id: string;
    status: Variant_upcoming_done_ongoing;
    tanggal: Time;
    judul: string;
    deskripsi: string;
    lokasi: string;
    fotoId: string;
}
export interface T__2 {
    id: string;
    bio: string;
    nama: string;
    jabatan: string;
    urutan: bigint;
    mataPelajaran: string;
    fotoId: string;
}
export interface T {
    id: string;
    status: Status;
    alamat: string;
    nama: string;
    nisn: string;
    angkatan: bigint;
    kelas: string;
    jurusan: string;
    fotoId: string;
}
export interface T__5 {
    id: string;
    tanggalUpload: Time;
    judul: string;
    deskripsi: string;
    kategori: string;
    fotoId: string;
}
export interface T__6 {
    tujuan: string;
    misi: string;
    visi: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Status {
    aktif = "aktif",
    alumni = "alumni"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_nasional_internasional_provinsi_kabupaten_sekolah {
    nasional = "nasional",
    internasional = "internasional",
    provinsi = "provinsi",
    kabupaten = "kabupaten",
    sekolah = "sekolah"
}
export enum Variant_upcoming_done_ongoing {
    upcoming = "upcoming",
    done = "done",
    ongoing = "ongoing"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGaleri(sessionToken: string, galeri: T__5): Promise<void>;
    addInformasi(sessionToken: string, informasi: T__4): Promise<void>;
    addKegiatan(sessionToken: string, kegiatan: T__3): Promise<void>;
    addPengajar(sessionToken: string, pengajar: T__2): Promise<void>;
    addPrestasi(sessionToken: string, prestasi: T__1): Promise<void>;
    addSiswa(sessionToken: string, siswa: T): Promise<void>;
    adminLogin(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogout(sessionToken: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteGaleri(sessionToken: string, id: string): Promise<void>;
    deleteInformasi(sessionToken: string, id: string): Promise<void>;
    deleteKegiatan(sessionToken: string, id: string): Promise<void>;
    deletePengajar(sessionToken: string, id: string): Promise<void>;
    deletePrestasi(sessionToken: string, id: string): Promise<void>;
    deleteSiswa(sessionToken: string, id: string): Promise<void>;
    getAllGaleri(): Promise<Array<T__5>>;
    getAllInformasi(sessionToken: string): Promise<Array<T__4>>;
    getAllKegiatan(): Promise<Array<T__3>>;
    getAllPengajar(): Promise<Array<T__2>>;
    getAllPesan(sessionToken: string): Promise<Array<T__8>>;
    getAllPrestasi(): Promise<Array<T__1>>;
    getAllSiswa(sessionToken: string): Promise<Array<T>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGaleriByKategori(kategori: string): Promise<Array<T__5>>;
    getKegiatanByStatus(status: Variant_upcoming_done_ongoing): Promise<Array<T__3>>;
    getKontak(): Promise<T__7 | null>;
    getPrestasiByTingkat(tingkat: Variant_nasional_internasional_provinsi_kabupaten_sekolah): Promise<Array<T__1>>;
    getProfil(): Promise<T__6 | null>;
    getPublishedInformasi(): Promise<Array<T__4>>;
    getSiswaByKelas(sessionToken: string, kelas: string): Promise<Array<T>>;
    getSiswaByStatus(sessionToken: string, status: Status): Promise<Array<T>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isSessionValid(sessionToken: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendPesan(nama: string, email: string, subjek: string, isi: string, timestamp: Time): Promise<void>;
    setAdminCredentials(username: string, password: string, caffeineAdminToken: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateGaleri(sessionToken: string, id: string, updated: T__5): Promise<void>;
    updateInformasi(sessionToken: string, id: string, updated: T__4): Promise<void>;
    updateKegiatan(sessionToken: string, id: string, updated: T__3): Promise<void>;
    updateKontak(sessionToken: string, alamat: string, telepon: string, email: string, jamOperasional: string, koordinat: string): Promise<void>;
    updatePengajar(sessionToken: string, id: string, updated: T__2): Promise<void>;
    updatePrestasi(sessionToken: string, id: string, updated: T__1): Promise<void>;
    updateProfil(sessionToken: string, visi: string, misi: string, tujuan: string): Promise<void>;
    updateSiswa(sessionToken: string, id: string, updated: T): Promise<void>;
}
import type { Status as _Status, T as _T, T__1 as _T__1, T__3 as _T__3, T__6 as _T__6, T__7 as _T__7, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGaleri(arg0: string, arg1: T__5): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGaleri(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGaleri(arg0, arg1);
            return result;
        }
    }
    async addInformasi(arg0: string, arg1: T__4): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInformasi(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInformasi(arg0, arg1);
            return result;
        }
    }
    async addKegiatan(arg0: string, arg1: T__3): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addKegiatan(arg0, to_candid_T__3_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKegiatan(arg0, to_candid_T__3_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPengajar(arg0: string, arg1: T__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPengajar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPengajar(arg0, arg1);
            return result;
        }
    }
    async addPrestasi(arg0: string, arg1: T__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPrestasi(arg0, to_candid_T__1_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPrestasi(arg0, to_candid_T__1_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addSiswa(arg0: string, arg1: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSiswa(arg0, to_candid_T_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSiswa(arg0, to_candid_T_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteGaleri(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGaleri(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGaleri(arg0, arg1);
            return result;
        }
    }
    async deleteInformasi(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInformasi(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInformasi(arg0, arg1);
            return result;
        }
    }
    async deleteKegiatan(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKegiatan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKegiatan(arg0, arg1);
            return result;
        }
    }
    async deletePengajar(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePengajar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePengajar(arg0, arg1);
            return result;
        }
    }
    async deletePrestasi(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrestasi(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrestasi(arg0, arg1);
            return result;
        }
    }
    async deleteSiswa(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSiswa(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSiswa(arg0, arg1);
            return result;
        }
    }
    async getAllGaleri(): Promise<Array<T__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGaleri();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGaleri();
            return result;
        }
    }
    async getAllInformasi(arg0: string): Promise<Array<T__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInformasi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInformasi(arg0);
            return result;
        }
    }
    async getAllKegiatan(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKegiatan();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKegiatan();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPengajar(): Promise<Array<T__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPengajar();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPengajar();
            return result;
        }
    }
    async getAllPesan(arg0: string): Promise<Array<T__8>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPesan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPesan(arg0);
            return result;
        }
    }
    async getAllPrestasi(): Promise<Array<T__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrestasi();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrestasi();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSiswa(arg0: string): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSiswa(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSiswa(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGaleriByKategori(arg0: string): Promise<Array<T__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGaleriByKategori(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGaleriByKategori(arg0);
            return result;
        }
    }
    async getKegiatanByStatus(arg0: Variant_upcoming_done_ongoing): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKegiatanByStatus(to_candid_variant_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKegiatanByStatus(to_candid_variant_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKontak(): Promise<T__7 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKontak();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKontak();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrestasiByTingkat(arg0: Variant_nasional_internasional_provinsi_kabupaten_sekolah): Promise<Array<T__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrestasiByTingkat(to_candid_variant_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrestasiByTingkat(to_candid_variant_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfil(): Promise<T__6 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfil();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfil();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedInformasi(): Promise<Array<T__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedInformasi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedInformasi();
            return result;
        }
    }
    async getSiswaByKelas(arg0: string, arg1: string): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiswaByKelas(arg0, arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiswaByKelas(arg0, arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiswaByStatus(arg0: string, arg1: Status): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiswaByStatus(arg0, to_candid_Status_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiswaByStatus(arg0, to_candid_Status_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSessionValid(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSessionValid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSessionValid(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendPesan(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendPesan(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendPesan(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async setAdminCredentials(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminCredentials(arg0, arg1, arg2);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminCredentials(arg0, arg1, arg2);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGaleri(arg0: string, arg1: string, arg2: T__5): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGaleri(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGaleri(arg0, arg1, arg2);
            return result;
        }
    }
    async updateInformasi(arg0: string, arg1: string, arg2: T__4): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInformasi(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInformasi(arg0, arg1, arg2);
            return result;
        }
    }
    async updateKegiatan(arg0: string, arg1: string, arg2: T__3): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKegiatan(arg0, arg1, to_candid_T__3_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKegiatan(arg0, arg1, to_candid_T__3_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateKontak(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKontak(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKontak(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePengajar(arg0: string, arg1: string, arg2: T__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePengajar(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePengajar(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePrestasi(arg0: string, arg1: string, arg2: T__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrestasi(arg0, arg1, to_candid_T__1_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrestasi(arg0, arg1, to_candid_T__1_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateProfil(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfil(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfil(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSiswa(arg0: string, arg1: string, arg2: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiswa(arg0, arg1, to_candid_T_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiswa(arg0, arg1, to_candid_T_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Status_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_T__1_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_T__3_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__3): T__3 {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_T_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__7]): T__7 | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__6]): T__6 | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        upcoming: null;
    } | {
        done: null;
    } | {
        ongoing: null;
    };
    tanggal: _Time;
    judul: string;
    deskripsi: string;
    lokasi: string;
    fotoId: string;
}): {
    id: string;
    status: Variant_upcoming_done_ongoing;
    tanggal: Time;
    judul: string;
    deskripsi: string;
    lokasi: string;
    fotoId: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        tanggal: value.tanggal,
        judul: value.judul,
        deskripsi: value.deskripsi,
        lokasi: value.lokasi,
        fotoId: value.fotoId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tahun: bigint;
    judul: string;
    deskripsi: string;
    tingkat: {
        nasional: null;
    } | {
        internasional: null;
    } | {
        provinsi: null;
    } | {
        kabupaten: null;
    } | {
        sekolah: null;
    };
    siswa: string;
    fotoId: string;
}): {
    id: string;
    tahun: bigint;
    judul: string;
    deskripsi: string;
    tingkat: Variant_nasional_internasional_provinsi_kabupaten_sekolah;
    siswa: string;
    fotoId: string;
} {
    return {
        id: value.id,
        tahun: value.tahun,
        judul: value.judul,
        deskripsi: value.deskripsi,
        tingkat: from_candid_variant_n28(_uploadFile, _downloadFile, value.tingkat),
        siswa: value.siswa,
        fotoId: value.fotoId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    alamat: string;
    nama: string;
    nisn: string;
    angkatan: bigint;
    kelas: string;
    jurusan: string;
    fotoId: string;
}): {
    id: string;
    status: Status;
    alamat: string;
    nama: string;
    nisn: string;
    angkatan: bigint;
    kelas: string;
    jurusan: string;
    fotoId: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n32(_uploadFile, _downloadFile, value.status),
        alamat: value.alamat,
        nama: value.nama,
        nisn: value.nisn,
        angkatan: value.angkatan,
        kelas: value.kelas,
        jurusan: value.jurusan,
        fotoId: value.fotoId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    done: null;
} | {
    ongoing: null;
}): Variant_upcoming_done_ongoing {
    return "upcoming" in value ? Variant_upcoming_done_ongoing.upcoming : "done" in value ? Variant_upcoming_done_ongoing.done : "ongoing" in value ? Variant_upcoming_done_ongoing.ongoing : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nasional: null;
} | {
    internasional: null;
} | {
    provinsi: null;
} | {
    kabupaten: null;
} | {
    sekolah: null;
}): Variant_nasional_internasional_provinsi_kabupaten_sekolah {
    return "nasional" in value ? Variant_nasional_internasional_provinsi_kabupaten_sekolah.nasional : "internasional" in value ? Variant_nasional_internasional_provinsi_kabupaten_sekolah.internasional : "provinsi" in value ? Variant_nasional_internasional_provinsi_kabupaten_sekolah.provinsi : "kabupaten" in value ? Variant_nasional_internasional_provinsi_kabupaten_sekolah.kabupaten : "sekolah" in value ? Variant_nasional_internasional_provinsi_kabupaten_sekolah.sekolah : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aktif: null;
} | {
    alumni: null;
}): Status {
    return "aktif" in value ? Status.aktif : "alumni" in value ? Status.alumni : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__3>): Array<T__3> {
    return value.map((x)=>from_candid_T__3_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__1>): Array<T__1> {
    return value.map((x)=>from_candid_T__1_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n30(_uploadFile, _downloadFile, x));
}
function to_candid_Status_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_T__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): _T__1 {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_T__3_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__3): _T__3 {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_T_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tahun: bigint;
    judul: string;
    deskripsi: string;
    tingkat: Variant_nasional_internasional_provinsi_kabupaten_sekolah;
    siswa: string;
    fotoId: string;
}): {
    id: string;
    tahun: bigint;
    judul: string;
    deskripsi: string;
    tingkat: {
        nasional: null;
    } | {
        internasional: null;
    } | {
        provinsi: null;
    } | {
        kabupaten: null;
    } | {
        sekolah: null;
    };
    siswa: string;
    fotoId: string;
} {
    return {
        id: value.id,
        tahun: value.tahun,
        judul: value.judul,
        deskripsi: value.deskripsi,
        tingkat: to_candid_variant_n13(_uploadFile, _downloadFile, value.tingkat),
        siswa: value.siswa,
        fotoId: value.fotoId
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status;
    alamat: string;
    nama: string;
    nisn: string;
    angkatan: bigint;
    kelas: string;
    jurusan: string;
    fotoId: string;
}): {
    id: string;
    status: _Status;
    alamat: string;
    nama: string;
    nisn: string;
    angkatan: bigint;
    kelas: string;
    jurusan: string;
    fotoId: string;
} {
    return {
        id: value.id,
        status: to_candid_Status_n16(_uploadFile, _downloadFile, value.status),
        alamat: value.alamat,
        nama: value.nama,
        nisn: value.nisn,
        angkatan: value.angkatan,
        kelas: value.kelas,
        jurusan: value.jurusan,
        fotoId: value.fotoId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_upcoming_done_ongoing;
    tanggal: Time;
    judul: string;
    deskripsi: string;
    lokasi: string;
    fotoId: string;
}): {
    id: string;
    status: {
        upcoming: null;
    } | {
        done: null;
    } | {
        ongoing: null;
    };
    tanggal: _Time;
    judul: string;
    deskripsi: string;
    lokasi: string;
    fotoId: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n10(_uploadFile, _downloadFile, value.status),
        tanggal: value.tanggal,
        judul: value.judul,
        deskripsi: value.deskripsi,
        lokasi: value.lokasi,
        fotoId: value.fotoId
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upcoming_done_ongoing): {
    upcoming: null;
} | {
    done: null;
} | {
    ongoing: null;
} {
    return value == Variant_upcoming_done_ongoing.upcoming ? {
        upcoming: null
    } : value == Variant_upcoming_done_ongoing.done ? {
        done: null
    } : value == Variant_upcoming_done_ongoing.ongoing ? {
        ongoing: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_nasional_internasional_provinsi_kabupaten_sekolah): {
    nasional: null;
} | {
    internasional: null;
} | {
    provinsi: null;
} | {
    kabupaten: null;
} | {
    sekolah: null;
} {
    return value == Variant_nasional_internasional_provinsi_kabupaten_sekolah.nasional ? {
        nasional: null
    } : value == Variant_nasional_internasional_provinsi_kabupaten_sekolah.internasional ? {
        internasional: null
    } : value == Variant_nasional_internasional_provinsi_kabupaten_sekolah.provinsi ? {
        provinsi: null
    } : value == Variant_nasional_internasional_provinsi_kabupaten_sekolah.kabupaten ? {
        kabupaten: null
    } : value == Variant_nasional_internasional_provinsi_kabupaten_sekolah.sekolah ? {
        sekolah: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    aktif: null;
} | {
    alumni: null;
} {
    return value == Status.aktif ? {
        aktif: null
    } : value == Status.alumni ? {
        alumni: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
